language: cpp
sudo: required
dist: trusty
compiler:
  - gcc
  - clang
os:
  - linux
addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-5.0
    packages:
    # install toolchains
    - clang-5.0
    - g++-7
    - libboost-dev
    - libboost-test-dev
    - libboost-program-options-dev
    - libc-ares-dev
    - libcurl4-openssl-dev
    - libgd-dev
    - libprotobuf-dev
    - libprotoc-dev
    - protobuf-compiler
    - zlib1g-dev
env:
  - BUILD_TYPE=debug
  - BUILD_TYPE=release
script:
  - if [ "$CXX" == "g++" ]; then export CXX="g++-7"; fi
  - if [ "$CXX" == "clang++" ]; then sudo apt remove libprotobuf-dev; fi
  - g++-7 -v
  - clang++-5.0 -v
  - ./build.sh
